### ISSUE TITLE
how to change screenbackground color

### ISSUE THREAD

**Issue by sallespro** [Domenicobrz/Blurry#4]
hi, i have tried to set backgroundColor in `globals.js`with no success.

```
// static background color (is additive with the rest of the scene)
var backgroundColor  = [255/255, 255/255, 255/255];
```

how can i render the scene with white background ?

**Comment by Domenicobrz** [comment]
Sorry for the late reply, colors are always additive, but I imagine the effect you're after can be obtained by adding:

`    gl_FragColor.rgb = 1.0 - gl_FragColor.rgb;`

on libs/shaders/postproc.js, at the end of the shader

**Comment by sallespro** [comment]
hi ! it's nice of you. 
it did turn the background to white, but also changed the orange to blue.
```
    gl_FragColor = vec4(uBackgroundColor + mapped, 1.0); 
    gl_FragColor.rgb = 1.0 - gl_FragColor.rgb;
```

**Comment by Domenicobrz** [comment]
Yeah that line essentially inverts every color that is outputted in the screen, so to get the orange back you need to invert the colors of your lines as well :)
If you originally had red as [1, 0, 0] now to output red again you'll have to write your "red" as: 
1 - [1,0,0] =
[0,1,1]
