### ISSUE TITLE
Animating geometry?

### ISSUE THREAD

**Issue by jzting** [Domenicobrz/Blurry#5]
Hi,

Really nice library! I was wondering if you had any tips to animate geometry in a performant manner?

 I started playing with the demos by trying to recompute lines and calling createLinesWrapper() at an interval but it seems to be a very expensive operation.

**Comment by Domenicobrz** [comment]
Sorry if I'm answering late, at the time unfortunately it took me 2-3 seconds per frame and I was basically saving these frames with the snippet here:
https://github.com/Domenicobrz/Blurry/blob/master/libs/main.js#L250

then I was mass editing all the images with xnConvert and used photoshop to make a gif out of all those pictures

**Comment by jzting** [comment]
Ah I see – I was hoping there was a way to do it real time. Thanks!
